config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :proponents do
    resources :proponent_documents, path: 'documents'
    resources :addresses
    resources :proponent_contacts, path: 'contacts'
  end
  post 'proponents/inss_discount', to: 'proponents#inss_discount'
  resources :dashboards, only: :index

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root 'proponents#index'
end

app/models/proponent.rb
# frozen_string_literal: true

class Proponent < ApplicationRecord
  INSS_LEVELS = %w[inss_level_1 inss_level_2 inss_level_3 inss_level_4].freeze

  INSS_DISCOUNT_LEVEL_1 = 0.075
  INSS_LEVEL_1_LIMIT = 1_412.0

  INSS_DISCOUNT_LEVEL_2 = 0.09
  INSS_LEVEL_2_LIMIT = 2_666.68

  INSS_DISCOUNT_LEVEL_3 = 0.12
  INSS_LEVEL_3_LIMIT = 4_000.03

  INSS_DISCOUNT_LEVEL_4 = 0.14
  INSS_LEVEL_4_LIMIT = 7_786.02

  scope :by_name, ->(name) { where('name ILIKE ?', "%#{name}%") }
  scope :by_inss_level, ->(inss_level) { where(inss_level: inss_level) }

  before_save :save_inss_discount

  validates :name, presence: true

  validates :birthdate, presence: true

  validates :income, numericality: { greater_than: 0 }

  has_many :addresses, as: :addressable, dependent: :destroy

  has_many :documents, class_name: 'ProponentDocument', dependent: :destroy

  has_many :contacts, class_name: 'ProponentContact', dependent: :destroy

  def translated_inss_level
    Proponent.translate_inss_level(inss_level)
  end

  def self.translate_inss_level(level)
    I18n.t("inss_levels.#{level}")
  end

  def self.calculate_inss_discount(income)
    rounded_income = income.to_d.round(2)
    return 0 if rounded_income <= 0

    # primeira faixa
    return (rounded_income * INSS_DISCOUNT_LEVEL_1).round(2) if rounded_income <= INSS_LEVEL_1_LIMIT

    first_level_discount = (INSS_LEVEL_1_LIMIT * INSS_DISCOUNT_LEVEL_1).round(2)

    # segunda faixa
    if rounded_income <= INSS_LEVEL_2_LIMIT
      return (((rounded_income - INSS_LEVEL_1_LIMIT) * INSS_DISCOUNT_LEVEL_2).round(2) + first_level_discount).round(2)
    end

    second_level_discount = ((INSS_LEVEL_2_LIMIT - INSS_LEVEL_1_LIMIT) * INSS_DISCOUNT_LEVEL_2).round(2)

    # terceira faixa
    if rounded_income <= INSS_LEVEL_3_LIMIT
      return (((rounded_income - INSS_LEVEL_2_LIMIT) * INSS_DISCOUNT_LEVEL_3).round(2) + first_level_discount + second_level_discount).round(2)
    end

    third_level_discount = ((INSS_LEVEL_3_LIMIT - INSS_LEVEL_2_LIMIT) * INSS_DISCOUNT_LEVEL_3).round(2)

    # quarta faixa
    if rounded_income <= INSS_LEVEL_4_LIMIT
      return (((rounded_income - INSS_LEVEL_3_LIMIT) * INSS_DISCOUNT_LEVEL_4).round(2) + first_level_discount + second_level_discount + third_level_discount).round(2)
    end

    fourth_level_discount = ((INSS_LEVEL_4_LIMIT - INSS_LEVEL_3_LIMIT) * INSS_DISCOUNT_LEVEL_4).round(2)

    (first_level_discount + second_level_discount + third_level_discount + fourth_level_discount).round(2)
  end

  private

    def save_inss_discount
      self.inss_discount = Proponent.calculate_inss_discount(income)
      rounded_income = income.to_d.round(2)
      self.inss_level = if rounded_income <= INSS_LEVEL_1_LIMIT
                          'inss_level_1'
                        elsif rounded_income <= INSS_LEVEL_2_LIMIT
                          'inss_level_2'
                        elsif rounded_income <= INSS_LEVEL_3_LIMIT
                          'inss_level_3'
                        else
                          'inss_level_4'
                        end
    end
end

app/controllers/proponents_controller.rb
class ProponentsController < ApplicationController
  include Pagy::Backend

  skip_before_action :verify_authenticity_token, only: :inss_discount
  before_action :set_proponent, only: %i[ show edit update destroy ]

  has_scope :by_name
  has_scope :by_inss_level

  # GET /proponents or /proponents.json
  def index
    @pagy, @proponents = pagy(apply_scopes(Proponent.all.order(:name)))
  end

  # GET /proponents/1 or /proponents/1.json
  def show
    @tab = params[:tab] || "personal"
  end

  # GET /proponents/new
  def new
    @proponent = Proponent.new
  end

  # GET /proponents/1/edit
  def edit
  end

  # POST /proponents or /proponents.json
  def create
    @proponent = Proponent.new(proponent_params)

    respond_to do |format|
      if @proponent.save
        format.html { redirect_to @proponent, notice: "Proponente foi criado com sucesso." }
        format.json { render :show, status: :created, location: @proponent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @proponent.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /proponents/inss_discount
  def inss_discount
    income = params[:income].to_f
    discount = Proponent.calculate_inss_discount(income)

    render json: { discount: discount }
  end

  # PATCH/PUT /proponents/1 or /proponents/1.json
  def update
    respond_to do |format|
      if @proponent.update(proponent_params)
        format.html { redirect_to @proponent, notice: "Proponente foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @proponent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @proponent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proponents/1 or /proponents/1.json
  def destroy
    @proponent.destroy!

    respond_to do |format|
      format.html { redirect_to proponents_path, status: :see_other, notice: "Proponente foi excluído com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proponent
      @proponent = Proponent.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def proponent_params
      params.expect(proponent: [ :name, :birthdate, :income ])
    end
end

app/helpers/proponents_helper.rb
module ProponentsHelper
end

app/views/proponents/_form.html.erb
<%= form_with(model: proponent, class: "row g-3") do |form| %>
  <% if proponent.errors.any? %>
    <div style="color: red">
      <ul>
        <% proponent.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-8">
    <%= form.text_field :name, class: "form-control", placeholder: "Nome" %>
  </div>

  <div class="col-4">
    <%= form.text_field :birthdate, class: "form-control", data: {
      controller: "flatpickr"}, placeholder: "Data de nascimento" %>
  </div>

  <div class="col-3">
    <%= form.text_field :income, class: "form-control", placeholder: "Salário", data: { controller: "inss", 
            inss_target: "input", 
            action: "blur->inss#calculate" } %>
  </div>

  <div id="discount-output" class="mt-3 d-none">
    <div class="alert alert-info" role="alert">
      <strong>Desconto INSS:</strong> <span id="calculated-inss-discount">0.00</span>
    </div>
  </div>

  <div class="col-12 pt-2 d-flex justify-content-end">
    <%= link_to "Proponentes", proponents_path, class: "btn btn-secondary text-uppercase me-3" %>
    <%= form.submit "Salvar", class: "btn btn-primary text-uppercase" %>
  </div>
<% end %>

app/views/proponents/_proponent.html.erb
<tr id="<%= dom_id proponent %>">
  <td><%= proponent.name %></td>
  <td><%= I18n.l(proponent.birthdate) %></td>
  <td><%= number_to_currency(proponent.income, precision: 2) %></td>
  <td><%= proponent.translated_inss_level %></td>
  <td><%= number_to_currency(proponent.inss_discount, precision: 2) %></td>
  <td>
    <%= link_to 'Detalhes', proponent %>
  </td>
</tr>

app/views/proponents/_show_addresses.erb
<div class="card mt-3">
  <div class="card-header">
    Endereços de <%= @proponent.name %>
  </div>
  <div class="card-body">
    <div id="addresses">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Tipo</th>
            <th scope="col">Logradouro</th>
            <th scope="col">Número</th>
            <th scope="col">Complemento</th>
            <th scope="col">Bairro</th>
            <th scope="col">Cidade</th>
            <th scope="col">Estado</th>
            <th scope="col">CEP</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% proponent.addresses.each do |address| %>
            <tr>
              <td><%= address.kind %></td>
              <td><%= address.street %></td>
              <td><%= address.number %></td>
              <td><%= address.complement %></td>
              <td><%= address.district %></td>
              <td><%= address.city %></td>
              <td><%= address.state %></td>
              <td><%= address.zip_code %></td>
                <td>
                  <div class="pt-2 d-flex justify-content-end">
                    <%= button_to "Excluir", proponent_address_path(@proponent, address), method: :delete, class: "btn btn-danger me-4  btn-sm text-uppercase" %>
                    <%= link_to "Editar", edit_proponent_address_path(@proponent, address), class: "btn btn-secondary text-uppercase  btn-sm" %>
                  </div>
                </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <%= link_to "Novo endereço", new_proponent_address_path(proponent), class: "btn btn-primary float-end text-uppercase btn-sm" %>
  </div>
</div>

app/views/proponents/_show_contacts.erb
<div class="card mt-3">
  <div class="card-header">
    Contatos de <%= @proponent.name %>
  </div>
  <div class="card-body">
    <div id="contacts">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Tipo</th>
            <th scope="col">Contato</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% proponent.contacts.each do |contact| %>
            <tr>
              <td><%= contact.kind %></td>
              <td><%= contact.value %></td>
                <td>
                  <div class="pt-2 d-flex justify-content-end">
                    <%= button_to "Excluir", proponent_proponent_contact_path(@proponent, contact), method: :delete, class: "btn btn-danger me-4  btn-sm text-uppercase" %>
                    <%= link_to "Editar", edit_proponent_proponent_contact_path(@proponent, contact), class: "btn btn-secondary text-uppercase  btn-sm" %>
                  </div>
                </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <%= link_to "Novo contato", new_proponent_proponent_contact_path(proponent), class: "btn btn-primary float-end text-uppercase btn-sm" %>
  </div>
</div>

app/views/proponents/_show_documents.html.erb
<div class="card mt-3">
  <div class="card-header">
    Documentos de <%= @proponent.name %>
  </div>
  <div class="card-body">
    <div id="documents">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Tipo</th>
            <th scope="col">Número</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% proponent.documents.each do |document| %>
            <tr>
              <td><%= document.kind %></td>
              <td><%= document.document %></td>
                <td>
                  <div class="pt-2 d-flex justify-content-end">
                    <%= button_to "Excluir", proponent_proponent_document_path(@proponent, document), method: :delete, class: "btn btn-danger me-4  btn-sm text-uppercase" %>
                    <%= link_to "Editar", edit_proponent_proponent_document_path(@proponent, document), class: "btn btn-secondary text-uppercase  btn-sm" %>
                  </div>
                </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <%= link_to "Novo documento", new_proponent_proponent_document_path(proponent), class: "btn btn-primary float-end text-uppercase btn-sm" %>
  </div>
</div>

app/views/proponents/_show_personal_info.html.erb
<div class="card mt-3">
  <div class="card-header">
    Dados pessoais de <%= proponent.name %>
  </div>
  <div class="card-body">
    <div class="row mb-3">
        <div class="col-md-8">
          <label class="form-label fw-bold">Nome:</label>
          <p class="form-control-plaintext"><%= proponent.name %></p>
        </div>

        <div class="col-md-4">
        <label class="form-label fw-bold">Data de nascimento:</label>
        <p class="form-control-plaintext"><%= I18n.l(proponent.birthdate) %></p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 mb-3">
        <label class="form-label fw-bold">Salário:</label>
        <p class="form-control-plaintext"><%= number_to_currency(proponent.income, precision: 2) %></p>
      </div>

      <div class="col-md-6 mb-3">
        <div class="alert alert-info" role="alert">
          <strong>Desconto INSS:</strong> <span><%= number_to_currency(proponent.inss_discount, precision: 2) %></span>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/proponents/edit.html.erb
<% content_for :title, "Editing proponent" %>

<h1>Editar proponente</h1>

<%= render "form", proponent: @proponent %>

app/views/proponents/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Proponentes" %>

<h1>Proponentes</h1>

<div id="proponents">
  <%= form_with url: proponents_path, method: :get, local: true, class: "mb-3" do |form| %>
    <div class="row">
      <div class="col-md-3">
        <%= form.text_field :by_name, value: params[:by_name], placeholder: "Nome", class: "form-control" %>
      </div>
      <div class="col-md-3">
        <%= form.select :by_inss_level, 
          options_for_select(Proponent::INSS_LEVELS.map{|level| [Proponent.translate_inss_level(level), level]}, params[:by_inss_level]), 
        { class: "form-select", aria: { label: "Faixa INSS" }, prompt: "Selecione uma faixa" }, class: "form-select"  %>
      </div>
      <div class="col-md-4 align-self-end">
        <%= submit_tag 'Pesquisar', class: 'btn btn-primary text-uppercase me-3' %>
        <%= link_to 'Limpar', proponents_path, class: 'btn btn-secondary ms-2 text-uppercase' %>
      </div>
    </div>
  <% end %>

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">Data de nascimento</th>
        <th scope="col">Salário</th>
        <th scope="col">Faixa INSS</th>
        <th scope="col">Desconto INSS</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @proponents.each do |proponent| %>
        <%= render proponent %>
      <% end %>
    </tbody>
  </table>

  <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
</div>

<%= link_to "Novo", new_proponent_path, class: "btn btn-primary float-end text-uppercase" %>

app/views/proponents/new.html.erb
<% content_for :title, "Novo proponente" %>

<h1>Novo proponente</h1>

<%= render "form", proponent: @proponent %>

app/views/proponents/show.html.erb
<% content_for :title, "Detalhes do proponente" %>

<p style="color: green"><%= notice %></p>

<div class="container my-5">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link <%= 'active' if @tab == 'personal' %>" id="personal-tab" data-bs-toggle="tab" data-bs-target="#personal" type="button" role="tab" aria-controls="personal" aria-selected="true">Dados pessoais</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link <%= 'active' if @tab == 'document' %>" id="document-tab" data-bs-toggle="tab" data-bs-target="#document" type="button" role="tab" aria-controls="document" aria-selected="false">Documentos</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link <%= 'active' if @tab == 'address' %>" id="address-tab" data-bs-toggle="tab" data-bs-target="#address" type="button" role="tab" aria-controls="address" aria-selected="false">Endereços</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link <%= 'active' if @tab == 'contact' %>" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button" role="tab" aria-controls="contact" aria-selected="false">Contatos</button>
    </li>
  </ul>

  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade <%= 'show active' if @tab == 'personal' %>" id="personal" role="tabpanel" aria-labelledby="personal-tab">
      <%= render "show_personal_info", proponent: @proponent %>
    </div>

    <div class="tab-pane fade <%= 'show active' if @tab == 'document' %>" id="document" role="tabpanel" aria-labelledby="document-tab">
      <%= render "show_documents", proponent: @proponent %>
    </div>

    <div class="tab-pane fade <%= 'show active' if @tab == 'address' %>" id="address" role="tabpanel" aria-labelledby="address-tab">
      <%= render "show_addresses", proponent: @proponent %>
    </div>

    <div class="tab-pane fade <%= 'show active' if @tab == 'contact' %>" id="contact" role="tabpanel" aria-labelledby="contact-tab">
      <%= render "show_contacts", proponent: @proponent %>
    </div>
  </div>
</div>

<div class="col-12 pt-2 d-flex justify-content-end">
  <%= button_to "Excluir", @proponent, method: :delete, class: "btn btn-danger me-4 text-uppercase" %>
  <%= link_to "Proponentes", proponents_path, class: "btn btn-secondary text-uppercase me-3" %>
  <%= link_to "Editar", edit_proponent_path(@proponent), class: "btn btn-primary text-uppercase" %>
</div>