config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :proponents do
    resources :proponent_documents, path: 'documents'
    resources :addresses
    resources :proponent_contacts, path: 'contacts'
  end
  post 'proponents/inss_discount', to: 'proponents#inss_discount'
  resources :dashboards, only: :index

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root 'proponents#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <header class="bg-primary text-white text-center py-3">
      <h1>Desconto INSS</h1>
    </header>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <% if authenticated? %>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-flex justify-content-center gap-4">
            <li class="nav-item">
              <%= link_to "Proponentes", proponents_path, class: "nav-link px-3 py-2 rounded-3 text-dark active" %>
            </li>
            <li class="nav-item">
              <%= link_to "Dashboards", dashboards_path, class: "nav-link px-3 py-2 rounded-3 text-dark" %>
            </li>
            <li class="nav-item">
              <%= button_to "Sair", session_path, method: :delete, class: "nav-link px-3 py-2 rounded-3 text-dark" if authenticated? %>
            </li>
          </ul>
        <% end %>
      </div>
    </nav>

    <main class="flex-grow-1 container-fluid my-4">
      <div id="content" class="px-4">
        <%= yield %>
      </div>
    </main>

    <footer class="bg-dark text-white text-center py-3">
      <p>&copy; 2024 Desconto INSS.</p>
    </footer>
  </body>
</html>